ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MT1,MDL_MH,MDL_MW1,MDL_MZ1,MDL_MW,MDL_MZ
     $ ,MDL_MB,MDL_MT,MDL_MH1

      COMMON/MASSES/ MDL_MT1,MDL_MH,MDL_MW1,MDL_MZ1,MDL_MW,MDL_MZ
     $ ,MDL_MB,MDL_MT,MDL_MH1


      DOUBLE PRECISION MDL_WH,MDL_WW,MDL_WZ,MDL_WW1,MDL_WZ1,MDL_WT
     $ ,MDL_WT1,MDL_WH1

      COMMON/WIDTHS/ MDL_WH,MDL_WW,MDL_WZ,MDL_WW1,MDL_WZ1,MDL_WT
     $ ,MDL_WT1,MDL_WH1


      DOUBLE COMPLEX GC_1, GC_2, GC_3, GC_135, GC_195, GC_196, GC_197,
     $  GC_223, GC_227, GC_284, GC_503, GC_504

      COMMON/COUPLINGS/ GC_1, GC_2, GC_3, GC_135, GC_195, GC_196,
     $  GC_197, GC_223, GC_227, GC_284, GC_503, GC_504

