ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MH,MDL_MW,MDL_MT,MDL_MB,MDL_MZ,MDL_MTA

      COMMON/MASSES/ MDL_MH,MDL_MW,MDL_MT,MDL_MB,MDL_MZ,MDL_MTA


      DOUBLE PRECISION MDL_WH,MDL_WW,MDL_WZ,MDL_WT

      COMMON/WIDTHS/ MDL_WH,MDL_WW,MDL_WZ,MDL_WT


      DOUBLE COMPLEX GC_1, GC_2, GC_3, GC_50, GC_58, GC_59, GC_81,
     $  GC_83

      COMMON/COUPLINGS/ GC_1, GC_2, GC_3, GC_50, GC_58, GC_59, GC_81,
     $  GC_83

