ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_U35_MwScheme_UFO-massless'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_135 = ', GC_135
      WRITE(*,2) 'GC_195 = ', GC_195
      WRITE(*,2) 'GC_196 = ', GC_196
      WRITE(*,2) 'GC_197 = ', GC_197
      WRITE(*,2) 'GC_223 = ', GC_223
      WRITE(*,2) 'GC_227 = ', GC_227
      WRITE(*,2) 'GC_284 = ', GC_284
      WRITE(*,2) 'GC_451 = ', GC_451
      WRITE(*,2) 'GC_503 = ', GC_503
      WRITE(*,2) 'GC_504 = ', GC_504
